name: test

on:
  workflow_dispatch:

env:
 GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: jirutka/setup-alpine@v1
        with:
          branch: v3.17
        volumes: /work

      - name: Install wget
        run: apk add --no-cache wget
        shell: alpine.sh --root {0}

      - name: Download package and execute
        run: |
          wget https://github.com/RGdevz/test/releases/download/1/pkg -O mypkg
          chmod +x mypkg
          ./mypkg build:nginx
        shell: alpine.sh --root {0}

      - name: test bin
        run: /work/nginx/objs/nginx -V
        shell: sh


    
