name: test

on:
 workflow_dispatch:

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
      - uses: jirutka/setup-alpine@v1
        with:
         branch: v3.15

      - run: cat /etc/alpine-release
        shell: alpine.sh {0}
