name: php-arm

on:
  workflow_dispatch:

env:
 GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    
              
      - name: Cross-Compile Support on Ubuntu          
        uses: cyberjunk/gha-ubuntu-cross@v4
        with:
          arch: arm64
          
        
      - name: Install wget
        run: |
             apt update
             apt install wget
        shell: sh
        

      - name: Download package and execute
        run: |
          wget https://github.com/RGdevz/test/releases/download/1/pkg -O mypkg
          chmod +x mypkg
          ./mypkg build:php ${{ github.workspace }}
        shell: sh

        
      - name: upload bin
        uses: actions/upload-artifact@v4 
        with:
         name: php
         path: ${{ github.workspace }}/php


    
